name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y openssh-server shellcheck zsh
      - if: runner.os == 'macOS'
        run: brew install shellcheck
      - run: test/run.sh
        env:
          SSHD: /usr/sbin/sshd
      - if: runner.os == 'Linux'
        run: test/docker.sh
